// <auto-generated />
using System;
using ConsoleAppCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleAppCore.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    partial class ShoppingListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleDatabaseContext.ShoppingList", b =>
                {
                    b.Property<int>("ShoppingListID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("UserProfileUserID");

                    b.HasKey("ShoppingListID");

                    b.HasIndex("UserProfileUserID");

                    b.ToTable("ShoppingList");
                });

            modelBuilder.Entity("ConsoleDatabaseContext.ShoppingListItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("ShoppingListID");

                    b.HasKey("ItemID");

                    b.HasIndex("ShoppingListID");

                    b.ToTable("ShoppingListItem");
                });

            modelBuilder.Entity("ConsoleDatabaseContext.UserProfile", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("UserID");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("ConsoleDatabaseContext.ShoppingList", b =>
                {
                    b.HasOne("ConsoleDatabaseContext.UserProfile")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserProfileUserID");
                });

            modelBuilder.Entity("ConsoleDatabaseContext.ShoppingListItem", b =>
                {
                    b.HasOne("ConsoleDatabaseContext.ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListID");
                });
#pragma warning restore 612, 618
        }
    }
}
